import { UserRole, UserStatus } from "./enum";

import { User } from "@/interfaces/interfaces";

// export const mock_columns: INF_TableColumn[] = [
//   { name: "ID", uid: "id", sortable: true },
//   { name: "NAME", uid: "name", sortable: true },
//   { name: "AGE", uid: "age", sortable: true },
//   { name: "ROLE", uid: "role", sortable: true },
//   { name: "TEAM", uid: "team" },
//   { name: "EMAIL", uid: "email" },
//   { name: "STATUS", uid: "status", sortable: true },
//   { name: "ACTIONS", uid: "actions" },
// ];

// export const mock_statusOptions: INF_Status[] = [
//   { name: "Active", uid: "active" },
//   { name: "Paused", uid: "paused" },
//   { name: "Vacation", uid: "vacation" },
// ];

// export const mock_users: INF_User[] = [
//   {
//     id: 1,
//     name: "Tony Reichert",
//     role: "CEO",
//     team: "Management",
//     status: "active",
//     age: "29",
//     email: "tony.reichert@example.com",
//   },
//   {
//     id: 2,
//     name: "Zoey Lang",
//     role: "Tech Lead",
//     team: "Development",
//     status: "paused",
//     age: "25",
//     email: "zoey.lang@example.com",
//   },
//   {
//     id: 3,
//     name: "Jane Fisher",
//     role: "Sr. Dev",
//     team: "Development",
//     status: "active",
//     age: "22",
//     email: "jane.fisher@example.com",
//   },
//   {
//     id: 4,
//     name: "William Howard",
//     role: "C.M.",
//     team: "Marketing",
//     status: "vacation",
//     age: "28",
//     email: "william.howard@example.com",
//   },
//   {
//     id: 5,
//     name: "Kristen Copper",
//     role: "S. Manager",
//     team: "Sales",
//     status: "active",
//     age: "24",
//     email: "kristen.cooper@example.com",
//   },
//   {
//     id: 6,
//     name: "Brian Kim",
//     role: "P. Manager",
//     team: "Management",
//     age: "29",
//     email: "brian.kim@example.com",
//     status: "Active",
//   },
//   {
//     id: 7,
//     name: "Michael Hunt",
//     role: "Designer",
//     team: "Design",
//     status: "paused",
//     age: "27",
//     email: "michael.hunt@example.com",
//   },
//   {
//     id: 8,
//     name: "Samantha Brooks",
//     role: "HR Manager",
//     team: "HR",
//     status: "active",
//     age: "31",
//     email: "samantha.brooks@example.com",
//   },
//   {
//     id: 9,
//     name: "Frank Harrison",
//     role: "F. Manager",
//     team: "Finance",
//     status: "vacation",
//     age: "33",
//     email: "frank.harrison@example.com",
//   },
//   {
//     id: 10,
//     name: "Emma Adams",
//     role: "Ops Manager",
//     team: "Operations",
//     status: "active",
//     age: "35",
//     email: "emma.adams@example.com",
//   },
//   {
//     id: 11,
//     name: "Brandon Stevens",
//     role: "Jr. Dev",
//     team: "Development",
//     status: "active",
//     age: "22",
//     email: "brandon.stevens@example.com",
//   },
//   {
//     id: 12,
//     name: "Megan Richards",
//     role: "P. Manager",
//     team: "Product",
//     status: "paused",
//     age: "28",
//     email: "megan.richards@example.com",
//   },
//   {
//     id: 13,
//     name: "Oliver Scott",
//     role: "S. Manager",
//     team: "Security",
//     status: "active",
//     age: "37",
//     email: "oliver.scott@example.com",
//   },
//   {
//     id: 14,
//     name: "Grace Allen",
//     role: "M. Specialist",
//     team: "Marketing",
//     status: "active",
//     age: "30",
//     email: "grace.allen@example.com",
//   },
//   {
//     id: 15,
//     name: "Noah Carter",
//     role: "IT Specialist",
//     team: "I. Technology",
//     status: "paused",
//     age: "31",
//     email: "noah.carter@example.com",
//   },
//   {
//     id: 16,
//     name: "Ava Perez",
//     role: "Manager",
//     team: "Sales",
//     status: "active",
//     age: "29",
//     email: "ava.perez@example.com",
//   },
//   {
//     id: 17,
//     name: "Liam Johnson",
//     role: "Data Analyst",
//     team: "Analysis",
//     status: "active",
//     age: "28",
//     email: "liam.johnson@example.com",
//   },
//   {
//     id: 18,
//     name: "Sophia Taylor",
//     role: "QA Analyst",
//     team: "Testing",
//     status: "active",
//     age: "27",
//     email: "sophia.taylor@example.com",
//   },
//   {
//     id: 19,
//     name: "Lucas Harris",
//     role: "Administrator",
//     team: "Information Technology",
//     status: "paused",
//     age: "32",
//     email: "lucas.harris@example.com",
//   },
//   {
//     id: 20,
//     name: "Mia Robinson",
//     role: "Coordinator",
//     team: "Operations",
//     status: "active",
//     age: "26",
//     email: "mia.robinson@example.com",
//   },
// ];

export const mock_users: User[] = [
  {
    id: 1,
    quota_number: "QN001",
    fullname: "พรงค์ทิพย์ แสงทอง",
    email: "prongtip.sangthong@example.com",
    phone: "012-345-6789",
    unit: 1,
    zone: "MDK",
    ae: "CT",
    role: UserRole.DepartmentHead,
    status: UserStatus.Working,
    leader_id: 0,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 2,
    quota_number: "QN256",
    fullname: "สมชาย ใจดี",
    email: "somchai.jaidee@example.com",
    phone: "012-345-6789",
    unit: 6,
    zone: "RN1",
    ae: "NE1",
    role: UserRole.DepartmentHead,
    status: UserStatus.Working,
    leader_id: 0,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 3,
    quota_number: "QN512",
    fullname: "สมหญิง ใจดี",
    email: "somying.jaidee@example.com",
    phone: "012-345-6789",
    unit: 4,
    zone: "RN2",
    ae: "NE2",
    role: UserRole.DepartmentHead,
    status: UserStatus.OnLeave,
    leader_id: 0,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 4,
    quota_number: "QN1024",
    fullname: "จิราภรณ์ แสงทอง",
    email: "jiraporn.sangthong@example.com",
    phone: "012-345-6789",
    unit: 1,
    zone: "MDK",
    ae: "CT",
    role: UserRole.UnitHead,
    status: UserStatus.Working,
    leader_id: 1,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 5,
    quota_number: "QN1025",
    fullname: "ภาณุพงศ์ มีสุข",
    email: "panupong.meesuk@example.com",
    phone: "023-456-7890",
    unit: 1,
    zone: "MDK",
    ae: "CT",
    role: UserRole.Driver,
    status: UserStatus.Working,
    leader_id: 4,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 6,
    quota_number: "QN1026",
    fullname: "กรรณิการ์ สมบูรณ์",
    email: "kannika.somboon@example.com",
    phone: "034-567-8901",
    unit: 1,
    zone: "MDK",
    ae: "CT",
    role: UserRole.Driver,
    status: UserStatus.OnLeave,
    leader_id: 4,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 7,
    quota_number: "QN1027",
    fullname: "สุรชัย วงศ์สวัสดิ์",
    email: "surachai.wongsawat@example.com",
    phone: "045-678-9012",
    unit: 1,
    zone: "MDK",
    ae: "CT",
    role: UserRole.Driver,
    status: UserStatus.Working,
    leader_id: 4,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 8,
    quota_number: "QN2048",
    fullname: "ธนพล สิทธิชัย",
    email: "tanapon.sittichai@example.com",
    phone: "056-789-0123",
    unit: 6,
    zone: "RN1",
    ae: "NE1",
    role: UserRole.UnitHead,
    status: UserStatus.Working,
    leader_id: 2,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 9,
    quota_number: "QN2049",
    fullname: "วรรณา คำใจ",
    email: "wanna.kamjai@example.com",
    phone: "067-890-1234",
    unit: 6,
    zone: "RN1",
    ae: "NE1",
    role: UserRole.Driver,
    status: UserStatus.OnLeave,
    leader_id: 8,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 10,
    quota_number: "QN2050",
    fullname: "อภิชาติ นามสกุล",
    email: "apichart.namsakul@example.com",
    phone: "078-901-2345",
    unit: 6,
    zone: "RN1",
    ae: "NE1",
    role: UserRole.Driver,
    status: UserStatus.Working,
    leader_id: 8,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 11,
    quota_number: "QN3072",
    fullname: "นิภา สุวรรณ",
    email: "nipa.suwan@example.com",
    phone: "089-012-3456",
    unit: 4,
    zone: "RN2",
    ae: "NE2",
    role: UserRole.UnitHead,
    status: UserStatus.Working,
    leader_id: 3,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 12,
    quota_number: "QN3073",
    fullname: "สมพงษ์ พงษ์เสถียร",
    email: "sompong.pongsathian@example.com",
    phone: "090-123-4567",
    unit: 4,
    zone: "RN2",
    ae: "NE2",
    role: UserRole.Driver,
    status: UserStatus.OnLeave,
    leader_id: 11,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 13,
    quota_number: "QN3074",
    fullname: "รัตนา สมบูรณ์",
    email: "rattana.somboon@example.com",
    phone: "091-234-5678",
    unit: 4,
    zone: "RN2",
    ae: "NE2",
    role: UserRole.Driver,
    status: UserStatus.Working,
    leader_id: 11,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 14,
    quota_number: "QN4096",
    fullname: "สมศักดิ์ จันทร์เพ็ญ",
    email: "somsak.chanpen@example.com",
    phone: "092-345-6789",
    unit: 8,
    zone: "BKK",
    ae: "CT",
    role: UserRole.DepartmentHead,
    status: UserStatus.Working,
    leader_id: 0,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 15,
    quota_number: "QN4097",
    fullname: "สุพัตรา เกษมสุข",
    email: "supattra.kasemsuk@example.com",
    phone: "093-456-7890",
    unit: 8,
    zone: "BKK",
    ae: "CT",
    role: UserRole.UnitHead,
    status: UserStatus.OnLeave,
    leader_id: 14,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 16,
    quota_number: "QN4098",
    fullname: "อนุชา รักษ์ไทย",
    email: "anucha.rakthai@example.com",
    phone: "094-567-8901",
    unit: 8,
    zone: "BKK",
    ae: "CT",
    role: UserRole.Driver,
    status: UserStatus.Working,
    leader_id: 15,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 17,
    quota_number: "QN5120",
    fullname: "ประภาส สิทธิพงษ์",
    email: "prapas.sitipong@example.com",
    phone: "095-678-9012",
    unit: 9,
    zone: "ESN",
    ae: "ES",
    role: UserRole.DepartmentHead,
    status: UserStatus.Working,
    leader_id: 0,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 18,
    quota_number: "QN5121",
    fullname: "สุนิสา มีสุข",
    email: "sunisa.meesuk@example.com",
    phone: "096-789-0123",
    unit: 9,
    zone: "ESN",
    ae: "ES",
    role: UserRole.UnitHead,
    status: UserStatus.Inactive,
    leader_id: 17,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 19,
    quota_number: "QN5122",
    fullname: "สมบัติ ใจดี",
    email: "sombat.jaidee@example.com",
    phone: "097-890-1234",
    unit: 9,
    zone: "ESN",
    ae: "ES",
    role: UserRole.Driver,
    status: UserStatus.Working,
    leader_id: 18,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 20,
    quota_number: "QN6144",
    fullname: "วีระชัย ภักดี",
    email: "weerachai.pakdee@example.com",
    phone: "098-901-2345",
    unit: 10,
    zone: "WSN",
    ae: "WS",
    role: UserRole.DepartmentHead,
    status: UserStatus.Working,
    leader_id: 0,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 21,
    quota_number: "QN6145",
    fullname: "ปิยะพร ศรีสุวรรณ",
    email: "piyaporn.srisuwan@example.com",
    phone: "099-012-3456",
    unit: 10,
    zone: "WSN",
    ae: "WS",
    role: UserRole.UnitHead,
    status: UserStatus.Inactive,
    leader_id: 20,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
];
