import {
  REQUESTORDERSTATUS,
  TASKORDERSTATUS,
  USERROLE,
  USERSTATUS,
} from "./enum";

import { RequestOrder, TaskOrder, User } from "@/interfaces/interfaces";

export const mock_users: User[] = [
  {
    id: 1,
    quota_number: "QN001",
    fullname: "พรงค์ทิพย์ แสงทอง",
    email: "prongtip.sangthong@example.com",
    phone: "012-345-6789",
    unit: 1,
    zone: "MDK",
    ae: "CT",
    role: USERROLE.DepartmentHead,
    status: USERSTATUS.Working,
    leader_id: 0,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 2,
    quota_number: "QN256",
    fullname: "สมชาย ใจดี",
    email: "somchai.jaidee@example.com",
    phone: "012-345-6789",
    unit: 6,
    zone: "RN1",
    ae: "NE1",
    role: USERROLE.DepartmentHead,
    status: USERSTATUS.Working,
    leader_id: 0,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 3,
    quota_number: "QN512",
    fullname: "สมหญิง ใจดี",
    email: "somying.jaidee@example.com",
    phone: "012-345-6789",
    unit: 4,
    zone: "RN2",
    ae: "NE2",
    role: USERROLE.DepartmentHead,
    status: USERSTATUS.OnLeave,
    leader_id: 0,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 4,
    quota_number: "QN1024",
    fullname: "จิราภรณ์ แสงทอง",
    email: "jiraporn.sangthong@example.com",
    phone: "012-345-6789",
    unit: 1,
    zone: "MDK",
    ae: "CT",
    role: USERROLE.UnitHead,
    status: USERSTATUS.Working,
    leader_id: 1,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 5,
    quota_number: "QN1025",
    fullname: "ภาณุพงศ์ มีสุข",
    email: "panupong.meesuk@example.com",
    phone: "023-456-7890",
    unit: 1,
    zone: "MDK",
    ae: "CT",
    role: USERROLE.Driver,
    status: USERSTATUS.Working,
    leader_id: 4,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 6,
    quota_number: "QN1026",
    fullname: "กรรณิการ์ สมบูรณ์",
    email: "kannika.somboon@example.com",
    phone: "034-567-8901",
    unit: 1,
    zone: "MDK",
    ae: "CT",
    role: USERROLE.Driver,
    status: USERSTATUS.OnLeave,
    leader_id: 4,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 7,
    quota_number: "QN1027",
    fullname: "สุรชัย วงศ์สวัสดิ์",
    email: "surachai.wongsawat@example.com",
    phone: "045-678-9012",
    unit: 1,
    zone: "MDK",
    ae: "CT",
    role: USERROLE.Driver,
    status: USERSTATUS.Working,
    leader_id: 4,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 8,
    quota_number: "QN2048",
    fullname: "ธนพล สิทธิชัย",
    email: "tanapon.sittichai@example.com",
    phone: "056-789-0123",
    unit: 6,
    zone: "RN1",
    ae: "NE1",
    role: USERROLE.UnitHead,
    status: USERSTATUS.Working,
    leader_id: 2,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 9,
    quota_number: "QN2049",
    fullname: "วรรณา คำใจ",
    email: "wanna.kamjai@example.com",
    phone: "067-890-1234",
    unit: 6,
    zone: "RN1",
    ae: "NE1",
    role: USERROLE.Driver,
    status: USERSTATUS.OnLeave,
    leader_id: 8,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 10,
    quota_number: "QN2050",
    fullname: "อภิชาติ นามสกุล",
    email: "apichart.namsakul@example.com",
    phone: "078-901-2345",
    unit: 6,
    zone: "RN1",
    ae: "NE1",
    role: USERROLE.Driver,
    status: USERSTATUS.Working,
    leader_id: 8,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 11,
    quota_number: "QN3072",
    fullname: "นิภา สุวรรณ",
    email: "nipa.suwan@example.com",
    phone: "089-012-3456",
    unit: 4,
    zone: "RN2",
    ae: "NE2",
    role: USERROLE.UnitHead,
    status: USERSTATUS.Working,
    leader_id: 3,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 12,
    quota_number: "QN3073",
    fullname: "สมพงษ์ พงษ์เสถียร",
    email: "sompong.pongsathian@example.com",
    phone: "090-123-4567",
    unit: 4,
    zone: "RN2",
    ae: "NE2",
    role: USERROLE.Driver,
    status: USERSTATUS.OnLeave,
    leader_id: 11,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 13,
    quota_number: "QN3074",
    fullname: "รัตนา สมบูรณ์",
    email: "rattana.somboon@example.com",
    phone: "091-234-5678",
    unit: 4,
    zone: "RN2",
    ae: "NE2",
    role: USERROLE.Driver,
    status: USERSTATUS.Working,
    leader_id: 11,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 14,
    quota_number: "QN4096",
    fullname: "สมศักดิ์ จันทร์เพ็ญ",
    email: "somsak.chanpen@example.com",
    phone: "092-345-6789",
    unit: 8,
    zone: "BKK",
    ae: "CT",
    role: USERROLE.DepartmentHead,
    status: USERSTATUS.Working,
    leader_id: 0,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 15,
    quota_number: "QN4097",
    fullname: "สุพัตรา เกษมสุข",
    email: "supattra.kasemsuk@example.com",
    phone: "093-456-7890",
    unit: 8,
    zone: "BKK",
    ae: "CT",
    role: USERROLE.UnitHead,
    status: USERSTATUS.OnLeave,
    leader_id: 14,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 16,
    quota_number: "QN4098",
    fullname: "อนุชา รักษ์ไทย",
    email: "anucha.rakthai@example.com",
    phone: "094-567-8901",
    unit: 8,
    zone: "BKK",
    ae: "CT",
    role: USERROLE.Driver,
    status: USERSTATUS.Working,
    leader_id: 15,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 17,
    quota_number: "QN5120",
    fullname: "ประภาส สิทธิพงษ์",
    email: "prapas.sitipong@example.com",
    phone: "095-678-9012",
    unit: 9,
    zone: "ESN",
    ae: "ES",
    role: USERROLE.DepartmentHead,
    status: USERSTATUS.Working,
    leader_id: 0,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 18,
    quota_number: "QN5121",
    fullname: "สุนิสา มีสุข",
    email: "sunisa.meesuk@example.com",
    phone: "096-789-0123",
    unit: 9,
    zone: "ESN",
    ae: "ES",
    role: USERROLE.UnitHead,
    status: USERSTATUS.Inactive,
    leader_id: 17,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 19,
    quota_number: "QN5122",
    fullname: "สมบัติ ใจดี",
    email: "sombat.jaidee@example.com",
    phone: "097-890-1234",
    unit: 9,
    zone: "ESN",
    ae: "ES",
    role: USERROLE.Driver,
    status: USERSTATUS.Working,
    leader_id: 18,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 20,
    quota_number: "QN6144",
    fullname: "วีระชัย ภักดี",
    email: "weerachai.pakdee@example.com",
    phone: "098-901-2345",
    unit: 10,
    zone: "WSN",
    ae: "WS",
    role: USERROLE.DepartmentHead,
    status: USERSTATUS.Working,
    leader_id: 0,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
  {
    id: 21,
    quota_number: "QN6145",
    fullname: "ปิยะพร ศรีสุวรรณ",
    email: "piyaporn.srisuwan@example.com",
    phone: "099-012-3456",
    unit: 10,
    zone: "WSN",
    ae: "WS",
    role: USERROLE.UnitHead,
    status: USERSTATUS.Inactive,
    leader_id: 20,
    active: true,
    created_at: new Date("2023-01-01T00:00:00Z"),
    updated_at: new Date("2023-01-02T00:00:00Z"),
    created_by: 0,
    updated_by: 0,
  },
];

export   const mockRequestOrders: RequestOrder[] = [
    {
      id: 1,
      customer_type: "FarmPro",
      affiliation: "บริษัท A",
      quota_number: "Q-001",
      farm_name: "ฟาร์ม 1",
      land_number: 101,
      activity_describe: "ไถพรวน",
      tool_describe: "รถไถ",
      ap_month_year: "2025-06",
      supervisor_fullname: "สมชาย ใจดี",
      unit: 1,
      zone: 1,
      ae: "CT",
      target_area: 50,
      actual_area: 48,
      on_live: true,
      evidence: undefined,
      sale: 10000,
      status: REQUESTORDERSTATUS.Created,
      supervisor_id: 10,
      location_id: 100,
      comment: "-",
      created_at: new Date("2025-06-01"),
      updated_at: new Date("2025-06-02"),
      created_by: 1,
      updated_by: 1,
    },
    {
      id: 2,
      customer_type: "CaneMIS",
      affiliation: "บริษัท B",
      quota_number: "Q-002",
      farm_name: "ฟาร์ม 2",
      land_number: 102,
      activity_describe: "หว่านปุ๋ย",
      tool_describe: "เครื่องหว่าน",
      ap_month_year: "2025-06",
      supervisor_fullname: "สมหญิง ดีใจ",
      unit: 2,
      zone: 2,
      ae: "NE1",
      target_area: 60,
      actual_area: 60,
      on_live: false,
      evidence: undefined,
      sale: 12000,
      status: REQUESTORDERSTATUS.PendingApproval,
      supervisor_id: 11,
      location_id: 101,
      comment: "-",
      created_at: new Date("2025-06-03"),
      updated_at: new Date("2025-06-04"),
      created_by: 2,
      updated_by: 2,
    },
    {
      id: 3,
      customer_type: "Songsirm",
      affiliation: "บริษัท C",
      quota_number: "Q-003",
      farm_name: "ฟาร์ม 3",
      land_number: 103,
      activity_describe: "เก็บเกี่ยว",
      tool_describe: "รถเกี่ยวข้าว",
      ap_month_year: "2025-07",
      supervisor_fullname: "สมปอง รักดี",
      unit: 3,
      zone: 3,
      ae: "NE2",
      target_area: 70,
      actual_area: 68,
      on_live: true,
      evidence: undefined,
      sale: 15000,
      status: REQUESTORDERSTATUS.PendingEdit,
      supervisor_id: 12,
      location_id: 102,
      comment: "ฝนตกหนัก",
      created_at: new Date("2025-07-01"),
      updated_at: new Date("2025-07-02"),
      created_by: 3,
      updated_by: 3,
    },
    {
      id: 4,
      customer_type: "FarmPro",
      affiliation: "บริษัท D",
      quota_number: "Q-004",
      farm_name: "ฟาร์ม 4",
      land_number: 104,
      activity_describe: "ปลูกข้าว",
      tool_describe: "เครื่องปลูก",
      ap_month_year: "2025-08",
      supervisor_fullname: "สมศักดิ์ กล้าหาญ",
      unit: 4,
      zone: 4,
      ae: "CT",
      target_area: 80,
      actual_area: 80,
      on_live: false,
      evidence: undefined,
      sale: 20000,
      status: REQUESTORDERSTATUS.Pending,
      supervisor_id: 13,
      location_id: 103,
      comment: "-",
      created_at: new Date("2025-08-01"),
      updated_at: new Date("2025-08-02"),
      created_by: 4,
      updated_by: 4,
    },
    {
      id: 5,
      customer_type: "CaneMIS",
      affiliation: "บริษัท E",
      quota_number: "Q-005",
      farm_name: "ฟาร์ม 5",
      land_number: 105,
      activity_describe: "ฉีดยาฆ่าแมลง",
      tool_describe: "โดรน",
      ap_month_year: "2025-09",
      supervisor_fullname: "สมฤดี สวยงาม",
      unit: 5,
      zone: 5,
      ae: "CT",
      target_area: 90,
      actual_area: 85,
      on_live: true,
      evidence: undefined,
      sale: 25000,
      status: REQUESTORDERSTATUS.InProgress,
      supervisor_id: 14,
      location_id: 104,
      comment: "งานเรียบร้อย",
      created_at: new Date("2025-09-01"),
      updated_at: new Date("2025-09-02"),
      created_by: 5,
      updated_by: 5,
    },
    {
      id: 6,
      customer_type: "Songsirm",
      affiliation: "บริษัท F",
      quota_number: "Q-006",
      farm_name: "ฟาร์ม 6",
      land_number: 106,
      activity_describe: "ตรวจสอบดิน",
      tool_describe: "เครื่องตรวจดิน",
      ap_month_year: "2025-10",
      supervisor_fullname: "สมหมาย ใจดี",
      unit: 6,
      zone: 6,
      ae: "NE2",
      target_area: 100,
      actual_area: 98,
      on_live: false,
      evidence: undefined,
      sale: 30000,
      status: REQUESTORDERSTATUS.PendingReview,
      supervisor_id: 15,
      location_id: 105,
      comment: "ลูกค้ายกเลิก",
      created_at: new Date("2025-10-01"),
      updated_at: new Date("2025-10-02"),
      created_by: 6,
      updated_by: 6,
    },
    {
      id: 7,
      customer_type: "FarmPro",
      affiliation: "บริษัท G",
      quota_number: "Q-007",
      farm_name: "ฟาร์ม 7",
      land_number: 107,
      activity_describe: "รดน้ำ",
      tool_describe: "ระบบน้ำหยด",
      ap_month_year: "2025-11",
      supervisor_fullname: "สมบัติ รักดี",
      unit: 7,
      zone: 7,
      ae: "NE1",
      target_area: 110,
      actual_area: 110,
      on_live: true,
      evidence: undefined,
      sale: 35000,
      status: REQUESTORDERSTATUS.PendingConfirm,
      supervisor_id: 16,
      location_id: 106,
      comment: "-",
      created_at: new Date("2025-11-01"),
      updated_at: new Date("2025-11-02"),
      created_by: 7,
      updated_by: 7,
    },
    {
      id: 8,
      customer_type: "CaneMIS",
      affiliation: "บริษัท H",
      quota_number: "Q-008",
      farm_name: "ฟาร์ม 8",
      land_number: 108,
      activity_describe: "เก็บเกี่ยว",
      tool_describe: "รถเกี่ยวข้าว",
      ap_month_year: "2025-12",
      supervisor_fullname: "สมศรี ดีใจ",
      unit: 8,
      zone: 8,
      ae: "NE2",
      target_area: 120,
      actual_area: 115,
      on_live: false,
      evidence: undefined,
      sale: 40000,
      status: REQUESTORDERSTATUS.Completed,
      supervisor_id: 17,
      location_id: 107,
      comment: "ผลผลิตดี",
      created_at: new Date("2025-12-01"),
      updated_at: new Date("2025-12-02"),
      created_by: 8,
      updated_by: 8,
    },
    {
      id: 9,
      customer_type: "Songsirm",
      affiliation: "บริษัท I",
      quota_number: "Q-009",
      farm_name: "ฟาร์ม 9",
      land_number: 109,
      activity_describe: "หว่านเมล็ด",
      tool_describe: "เครื่องหว่าน",
      ap_month_year: "2026-01",
      supervisor_fullname: "สมศักดิ์ ใจดี",
      unit: 9,
      zone: 9,
      ae: "CT",
      target_area: 130,
      actual_area: 120,
      on_live: true,
      evidence: undefined,
      sale: 45000,
      status: REQUESTORDERSTATUS.Rejected,
      supervisor_id: 18,
      location_id: 108,
      comment: "ไม่ผ่านการอนุมัติ",
      created_at: new Date("2026-01-01"),
      updated_at: new Date("2026-01-02"),
      created_by: 9,
      updated_by: 9,
    },
  ];

export const mock_taskorders: TaskOrder[] = [
  {
    id: 1,
    area_number: "A1254-001",
    area_target: 15,
    area_actual: 14.5,
    price: 5500,
    ap_date: new Date("2025-05-20T08:00:00Z"),
    oil_slip: "OS-25052023-001",
    oil_start_mile: 23456,
    start_mile: 23456,
    end_mile: 23498,
    oil_start: 80,
    oil_end: 65,
    car_start_hour: "0823",
    car_end_hour: "1415",
    start_timer: "08:30",
    end_timer: "14:00",
    status: TASKORDERSTATUS.Completed,
    request_order_id: 1,
    car_id: 3,
    tool_id: 2,
    assigned_user_id: 10,
    comment: "พื้นที่มีน้ำขัง บางส่วนเข้าถึงยาก",
    created_at: new Date("2025-05-18T07:15:00Z"),
    updated_at: new Date("2025-05-20T14:30:00Z"),
    created_by: 8,
    updated_by: 10,
  },
  {
    id: 2,
    area_number: "A1254-002",
    area_target: 8,
    area_actual: 7.2,
    price: 4200,
    ap_date: new Date("2025-05-25T09:00:00Z"),
    oil_slip: "OS-25052023-015",
    oil_start_mile: 24512,
    start_mile: 24512,
    end_mile: 24612,
    oil_start: 75,
    oil_end: 42,
    car_start_hour: "0915",
    car_end_hour: "0916",
    start_timer: "09:20",
    end_timer: "09:45",
    status: TASKORDERSTATUS.InProgress,
    request_order_id: 1,
    car_id: 5,
    tool_id: 2,
    assigned_user_id: 13,
    comment: "พื้นที่มีน้ำขัง บางส่วนเข้าถึงยาก",
    created_at: new Date("2025-05-23T16:40:00Z"),
    updated_at: new Date("2025-05-25T09:25:00Z"),
    created_by: 8,
    updated_by: 13,
  },
];
