import type {
  FieldConfig,
  StatusConfig,
  RequestOrder,
} from "@/interfaces/interfaces";

import React from "react";

import { REQUESTORDERSTATUS } from "@/utils/enum";
import Header from "@/components/Header";
import { CardComponent } from "@/components/CardComponent";
import { RequestOrderTranslation } from "@/utils/constants";

function OrderPage() {
  const headerFields: FieldConfig[] = [
    {
      key: "customer_type",
      label: "Customer Type",
      className: "font-bold text-lg text-left",
      translation: RequestOrderTranslation,
    },
    {
      key: "affiliation",
      label: "Affiliation",
      className: "font-medium text-left",
      translation: RequestOrderTranslation,
    },
    {
      key: "quota_number",
      label: "Quota #",
      className: "font-medium text-left",
      translation: RequestOrderTranslation,
    },
    {
      key: "farm_name",
      label: "Farm Name",
      className: "font-medium text-left",
      translation: RequestOrderTranslation,
    },
  ];

  const bodyFields: FieldConfig[] = [
    {
      key: "ap_month_year",
      label: "Month/Year",
      className: "text-left text-gray-600",
      translation: RequestOrderTranslation,
    },
    {
      key: "supervisor_fullname",
      label: "Supervisor",
      className: "text-left text-gray-600",
      translation: RequestOrderTranslation,
    },
    {
      key: "target_area",
      label: "Target Area",
      className: "text-left text-gray-600",
      translation: RequestOrderTranslation,
    },
  ];

  const mockData: RequestOrder[] = [
    {
      id: 1,
      customer_type: "FarmPro",
      affiliation: "บริษัท A",
      quota_number: "Q-001",
      farm_name: "ฟาร์ม 1",
      land_number: 101,
      activity_describe: "ไถพรวน",
      tool_describe: "รถไถ",
      ap_month_year: "2025-06",
      supervisor_fullname: "สมชาย ใจดี",
      unit: 1,
      zone: 1,
      ae: "CT",
      target_area: 50,
      actual_area: 48,
      on_live: true,
      evidence: undefined,
      sale: 10000,
      status: REQUESTORDERSTATUS.Pending,
      supervisor_id: 10,
      location_id: 100,
      comment: "-",
      created_at: new Date("2025-06-01"),
      updated_at: new Date("2025-06-02"),
      created_by: 1,
      updated_by: 1,
    },
    {
      id: 2,
      customer_type: "CaneMIS",
      affiliation: "บริษัท B",
      quota_number: "Q-002",
      farm_name: "ฟาร์ม 2",
      land_number: 102,
      activity_describe: "หว่านปุ๋ย",
      tool_describe: "เครื่องหว่าน",
      ap_month_year: "2025-06",
      supervisor_fullname: "สมหญิง ดีใจ",
      unit: 2,
      zone: 2,
      ae: "NE1",
      target_area: 60,
      actual_area: 60,
      on_live: false,
      evidence: undefined,
      sale: 12000,
      status: REQUESTORDERSTATUS.Completed,
      supervisor_id: 11,
      location_id: 101,
      comment: "-",
      created_at: new Date("2025-06-03"),
      updated_at: new Date("2025-06-04"),
      created_by: 2,
      updated_by: 2,
    },
    {
      id: 3,
      customer_type: "Songsirm",
      affiliation: "บริษัท C",
      quota_number: "Q-003",
      farm_name: "ฟาร์ม 3",
      land_number: 103,
      activity_describe: "เก็บเกี่ยว",
      tool_describe: "รถเกี่ยวข้าว",
      ap_month_year: "2025-07",
      supervisor_fullname: "สมปอง รักดี",
      unit: 3,
      zone: 3,
      ae: "NE2",
      target_area: 70,
      actual_area: 68,
      on_live: true,
      evidence: undefined,
      sale: 15000,
      status: REQUESTORDERSTATUS.Rejected,
      supervisor_id: 12,
      location_id: 102,
      comment: "ฝนตกหนัก",
      created_at: new Date("2025-07-01"),
      updated_at: new Date("2025-07-02"),
      created_by: 3,
      updated_by: 3,
    },
    {
      id: 4,
      customer_type: "FarmPro",
      affiliation: "บริษัท D",
      quota_number: "Q-004",
      farm_name: "ฟาร์ม 4",
      land_number: 104,
      activity_describe: "ปลูกข้าว",
      tool_describe: "เครื่องปลูก",
      ap_month_year: "2025-08",
      supervisor_fullname: "สมศักดิ์ กล้าหาญ",
      unit: 4,
      zone: 4,
      ae: "CT",
      target_area: 80,
      actual_area: 80,
      on_live: false,
      evidence: undefined,
      sale: 20000,
      status: REQUESTORDERSTATUS.Pending,
      supervisor_id: 13,
      location_id: 103,
      comment: "-",
      created_at: new Date("2025-08-01"),
      updated_at: new Date("2025-08-02"),
      created_by: 4,
      updated_by: 4,
    },
    {
      id: 5,
      customer_type: "CaneMIS",
      affiliation: "บริษัท E",
      quota_number: "Q-005",
      farm_name: "ฟาร์ม 5",
      land_number: 105,
      activity_describe: "ฉีดยาฆ่าแมลง",
      tool_describe: "โดรน",
      ap_month_year: "2025-09",
      supervisor_fullname: "สมฤดี สวยงาม",
      unit: 5,
      zone: 5,
      ae: "CT",
      target_area: 90,
      actual_area: 85,
      on_live: true,
      evidence: undefined,
      sale: 25000,
      status: REQUESTORDERSTATUS.Completed,
      supervisor_id: 14,
      location_id: 104,
      comment: "งานเรียบร้อย",
      created_at: new Date("2025-09-01"),
      updated_at: new Date("2025-09-02"),
      created_by: 5,
      updated_by: 5,
    },
    {
      id: 6,
      customer_type: "Songsirm",
      affiliation: "บริษัท F",
      quota_number: "Q-006",
      farm_name: "ฟาร์ม 6",
      land_number: 106,
      activity_describe: "ตรวจสอบดิน",
      tool_describe: "เครื่องตรวจดิน",
      ap_month_year: "2025-10",
      supervisor_fullname: "สมหมาย ใจดี",
      unit: 6,
      zone: 6,
      ae: "NE2",
      target_area: 100,
      actual_area: 98,
      on_live: false,
      evidence: undefined,
      sale: 30000,
      status: REQUESTORDERSTATUS.PendingReview,
      supervisor_id: 15,
      location_id: 105,
      comment: "ลูกค้ายกเลิก",
      created_at: new Date("2025-10-01"),
      updated_at: new Date("2025-10-02"),
      created_by: 6,
      updated_by: 6,
    },
    {
      id: 7,
      customer_type: "FarmPro",
      affiliation: "บริษัท G",
      quota_number: "Q-007",
      farm_name: "ฟาร์ม 7",
      land_number: 107,
      activity_describe: "รดน้ำ",
      tool_describe: "ระบบน้ำหยด",
      ap_month_year: "2025-11",
      supervisor_fullname: "สมบัติ รักดี",
      unit: 7,
      zone: 7,
      ae: "NE1",
      target_area: 110,
      actual_area: 110,
      on_live: true,
      evidence: undefined,
      sale: 35000,
      status: REQUESTORDERSTATUS.Pending,
      supervisor_id: 16,
      location_id: 106,
      comment: "-",
      created_at: new Date("2025-11-01"),
      updated_at: new Date("2025-11-02"),
      created_by: 7,
      updated_by: 7,
    },
    {
      id: 8,
      customer_type: "CaneMIS",
      affiliation: "บริษัท H",
      quota_number: "Q-008",
      farm_name: "ฟาร์ม 8",
      land_number: 108,
      activity_describe: "เก็บเกี่ยว",
      tool_describe: "รถเกี่ยวข้าว",
      ap_month_year: "2025-12",
      supervisor_fullname: "สมศรี ดีใจ",
      unit: 8,
      zone: 8,
      ae: "NE2",
      target_area: 120,
      actual_area: 115,
      on_live: false,
      evidence: undefined,
      sale: 40000,
      status: REQUESTORDERSTATUS.Completed,
      supervisor_id: 17,
      location_id: 107,
      comment: "ผลผลิตดี",
      created_at: new Date("2025-12-01"),
      updated_at: new Date("2025-12-02"),
      created_by: 8,
      updated_by: 8,
    },
  ];

  const statusConfig: StatusConfig = {
    key: "status",
    colorMap: {
      pending: "warning",
      completed: "success",
      cancelled: "danger",
    },
    translation: {
      pending: "Pending",
      completed: "Completed",
      cancelled: "Cancelled",
    },
  };

  return (
    <div className="w-full px-0">
      <Header subtitle="Please review your order" title="Order Page" />
      <CardComponent
        isActionsPage={true}
        bodyFields={bodyFields}
        headerFields={headerFields}
        items={mockData}
        statusConfig={statusConfig}
      />
    </div>
  );
}

export default OrderPage;
